# Generated by Django 5.2.1 on 2025-06-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='memeber_id',
            new_name='member_id',
        ),
    ]
