# Generated by Django 5.2.1 on 2025-06-04 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_memeber_id_userprofile_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Full UUID for internal use', unique=True, verbose_name='Full UUID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='member_id',
            field=models.CharField(editable=False, help_text='Short unique member ID for the user', max_length=8, unique=True, verbose_name='member ID'),
        ),
    ]
