# Generated by Django 5.2.1 on 2025-06-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_full_uuid_alter_userprofile_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership_level',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='phone number'),
        ),
    ]
